name: "JIRA Check Action"
description: "GitHub Action for checking that the PR title has a JIRA issue prefixed"
branding:
  icon: "check-square"
  color: "orange"
runs:
  using: "composite"
  steps:
    - id: run
      run: $GITHUB_ACTION_PATH/entrypoint.sh "${{ github.event.pull_request.title }}"
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
